### ISSUE TITLE
CGO Dependency

### ISSUE THREAD

**Issue by kishaningithub** [nalgeon/redka#12]
Can CGO dependency be removed? this will greatly improve the portability 

https://gitlab.com/cznic/sqlite

This library above is a CGO free port of sqlite

**Comment by nalgeon** [comment]
The `github.com/mattn/go-sqlite3` is optional if you use Redka as a Go module. You can use any other driver. This is addressed [in the docs](https://github.com/nalgeon/redka#go-module):

> You'll also need an SQLite driver. Use `github.com/mattn/go-sqlite3` if you don't mind CGO. Otherwise use a pure Go driver `modernc.org/sqlite`.

There is also a CGO-free usage example in [example/modernc/main.go](https://github.com/nalgeon/redka/blob/main/example/modernc/main.go).
