### ISSUE TITLE
compatibility tests

### ISSUE THREAD

**Issue by jtarchie** [nalgeon/redka#14]
Hey!

I was also building a Redis-protocol-sqlite-backed thingy from a previous project I worked on but (sort of) abandoned.

I built some tooling for the compatibility layer. Using this [project](https://github.com/tair-opensource/compatibility-test-suite-for-redis), where they have many test cases for the Redis compatibility layer for sets of commands and expected output.

It helps identify what is missing, what Redis version of the command(s) was introduced, etc.

I want to make a PR to show how it could be used.

**Comment by jtarchie** [comment]
Within the `cts.json` from the PR, the `since` value shows the version the commands are expected to have existed.

**Comment by nalgeon** [comment]
Thank you for the suggestion! I'm not aiming for 100% (or even close to 100%) compatibility with Redis, so I'll pass. There may be some kind of compatibility test later, but it's definitely too early for that now.

**Comment by jtarchie** [comment]
Sorry, it wasn't meant for 100% compatibility. It was meant to show community resources to validate the protocol.
