### ISSUE TITLE
LUA scripting

### ISSUE THREAD

**Issue by alturkovic** [nalgeon/redka#21]
This seems like a huge feature to drop.

LUA scripting is the preferred way (and the only one as far as I know) to implement conditional atomic execution.
A lot of libraries built on top of Redis rely on custom LUA scripts so Redka is not a suitable replacement for most of these.
Not having LUA scripting means that there is no way to implement any conditional atomic operations on top of the existing ones.

For an example: set key `foo` if `bar` does not exist. This could be implemented with LUA very easily, but I do not see how to implement such feature with Redka.

Not having an option to extend Redis with LUA scripts is very limiting and is one of the main features (IMHO) that makes Redis what it is.

Is there any way you could re-evaluate your position on supporting LUA scripts?

**Comment by nalgeon** [comment]
> but I do not see how to implement such feature with Redka.

With transactions — as long as you use the Go module:

```go
db.Update(func(tx *redka.Tx) error {
    barExists, err := tx.Key().Exists("bar")
    if err != nil {
        return err
    }
    if barExists {
        return nil
    }
    // Set foo if bar does not exist.
    return tx.Str().Set("foo", "foo")
})
```

> Is there any way you could re-evaluate your position on supporting LUA scripts?

There is: if/when there is a reasonable amount of people who _already_ using Redka in production, and _real-world_ use cases they can't implement without Lua scripting. Which is currently not the case.

**Comment by alturkovic** [comment]
> With transactions — as long as you use the Go module

I was hoping to use this from non-Go projects where it would not be supported.

> There is: if/when there is a reasonable amount of people who already using Redka in production, and real-world use cases they can't implement without Lua scripting. Which is currently not the case.

Fair enough, thank you for the quick reply :)
