### ISSUE TITLE
Implement the MONITOR command

### ISSUE THREAD

**Issue by kevin-cantwell** [nalgeon/redka#23]
First off, thanks for building this! I'd like to help contribute in any small way I can and I thought I'd start by offering an implementation for MONITOR.

Imo this is a good command to include as it doesn't have any effect on the underlying DB yet it's generally a useful feature for debugging and inspection. 

I believe the implementation for this can be fairly straightforward and `redcon` friendly. When the "monitor" command is detected it should detach the connection and subscribe it to all subsequent commands handled by the server. This means changing a the handler chain a little bit as well as handling the detached conn in a goroutine (for example detecting "quit" commands via a telnet).

PR incoming.

**Comment by nalgeon** [comment]
Hey Kevin, thank you for your interest in Redka! I wish we could have discussed this before you put your time and effort into the PR (hence the "please first open an issue" in the "contributing" section of the readme).

Redis has a lot of extra features, and I don't want to add new ones without a very good reason. The `monitor` command strikes me as an exotic with little practical use. It's probably better to just use logging to see all the commands executed by the server.

Sorry about this.

**Comment by kevin-cantwell** [comment]
No worries, it helped me get familiar with it. I might take a stab at publish/subscribe or hyperloglog if you still want those.

**Comment by nalgeon** [comment]
Let's get back to this after 1.0, please. Sorry again for being picky about the scope.
