### ISSUE TITLE
ZRANGE seems to have bug that not work with range 0 -1

### ISSUE THREAD

**Issue by Jianghong-bgcg** [nalgeon/redka#27]
I'm using the 0.5 ver of redka, and when I play around with redis official doc, it seems `ZRANGE key 0 -1` doesn't work:

```
root@US06-199W-74732:redka# redis-cli
127.0.0.1:6379> keys "*"
1) "racer_scores"
127.0.0.1:6379> type racer_scores
zset
127.0.0.1:6379> ZRANGE racer_scores 0 -1
(empty array)
127.0.0.1:6379> ZRANGE racer_scores 0 -1 WITHSCORES
Error: Server closed the connection
127.0.0.1:6379> ZRANGEBYSCORE racer_scores -inf 10
Could not connect to Redis at 127.0.0.1:6379: Connection refused
```
Redka kills itself afterwards.  
However if I run the ZRANGEBYSCORE command it does have value, meaning it's not my input that's corrupt
```
127.0.0.1:6379> ZRANGEBYSCORE racer_scores -inf 10
1) "Ford"
2) "Sam-Bodden"
3) "Norem"
4) "Royce"
```

**Comment by nalgeon** [comment]
`zrange` in Redka does not support negative `start` and `stop` parameters when ranging by rank, so this is the expected result:

```text
> zrange racer_scores 0 -1
(empty array)

> zrange racer_scores 0 -1 withscores
(empty array)
```

Crashing on `WITHSCORES` is a bug, I'll fix it.
