### ISSUE TITLE
Option to start without migration?

### ISSUE THREAD

**Issue by adoublef** [nalgeon/redka#30]
As the title suggests, would be interested if the API can be modified to allow users to open a connection and run the initial table creations separately.

The use-case is a tool such as [LiteFS](https://github.com/superfly/litefs/), a SQLite replication package. This currently limits one writer to the database on server creation. A problem arises with this package when spinning up a replica

```sh
2024-06-27 23:19:11 failed to create kv client: disk I/O error: permission denied
2024-06-27 23:19:11 level=INFO msg="E6A5861BC03876BC: disconnected from primary with error, retrying: next frame: context canceled"
```

This could likely be resolved by giving an option to ignore calling `sqlx.*DB[T].createSchema` pass by through the `redka.Options` struct.

A package level function could likely be exported instead to run the function:

```go
// Up as an example
func Up[T any](db *DB[T]) error {
    return d.createSchema()
}
```

giving a bit more flexibility to the application developer.

**Comment by nalgeon** [comment]
Not sure if I understand the use case correctly. Are you running Redka on the read-only database replica? Do you plan to only use API methods like Get, and not methods like Set or Delete?

**Comment by adoublef** [comment]
Yes, when a cluster of Go binaries are up, the leader will be granted read-write access, while all the replicas will be in read-only. The LiteFS package intercepts all sqlite operations to handle this. 

Having checked through the API of Redka again, I realise it would additionally require modifying the `*DB.startBgManager` functionality, as this would have read-only replicas, attempt writes, resulting in a permission denied. 

Similarly, if a leader is changed (via consensus) then that will now be promoted to perform read & writes. This is not something I considered before making the issue, and so unsure if this can be achieved without injecting very LiteFS specific code (they offer a way for a node to know if its a parent, but I'd expect this is not something that could be added to a general purpose library), so something I need to rethink.

Here is [an example project on Fly's profile](https://github.com/superfly/litefs-example/tree/main) using the standard `database/sql` interface.

**Comment by adoublef** [comment]
Regarding needing to know if a DB has been promoted, if the logic could be in application space and either an atomic value or a public field can be dynamically updated, then this could allow the application to run a go routine to look for these changes, reducing the work this library would need to do. 

```go
// pseudo-code
go func () {
  // user will look for changes in the filesystem
  // can be accomplished with an interval or hooking into litefs events
  // but this would be all within application space, not the library
  isPrimary, _  := nodeIsPrimary(ctx)
  if isPrimary { 
    kv.Mode(redka.Write)
  }
} () 
```

**Comment by nalgeon** [comment]
I see, thanks for the detailed explanation! I'll think about it over the weekend and hopefully come back with something.

**Comment by adoublef** [comment]
I think could work, I have an example project setup with litefs that I can experiment with. To me, I should be able to open a go routine in `main` as example, and have it just listen into the event stream that litefs offers. 

Would this `OpenRead` be a different type or just one that doesn't create the schema (or runs the purge). 

This would likely mean reassigning the `db` variable, something I've not had to do before, so will be willing to test this doesn't cause any unexpected behaviours. I have a simple redka+litefs example that to test this all with

**Comment by nalgeon** [comment]
Please try using `OpenRead` from the [read-only-mode](https://github.com/nalgeon/redka/tree/read-only-mode) branch. You can install it using `go get` as follows:

```text
go get github.com/nalgeon/redka@read-only-mode
```

`OpenRead` returns the same `*redka.DB` value as `Open`, only the write operations won't work:

```go
// open a writable database
db, err := redka.Open("data.db", nil)
if err != nil {
    panic(err)
}
db.Str().Set("name", "alice")
db.Close()

// open a read-only database
db, err = redka.OpenRead("data.db", nil)
if err != nil {
    panic(err)
}

// read operations work fine
name, _ := db.Str().Get("name")
fmt.Println(name)

// write operations will fail
err = db.Str().Set("name", "bob")
fmt.Println(err)
db.Close()
```

```text
alice
attempt to write a readonly database
```

**Comment by nalgeon** [comment]
Any luck trying `OpenRead`?
