### ISSUE TITLE
Does not work with Tiny RDM

### ISSUE THREAD

**Issue by BingCoke** [nalgeon/redka#37]
i cannot use redis gui to look data. it show this log: time=2024-09-24T19:42:13.600+08:00 level=WARN msg="run single command" client=127.0.0.1:56373 name=config err="ERR unknown command"

**Comment by nalgeon** [comment]
What is "redis gui"? Please provide a link to the specific tool you are using.

**Comment by BingCoke** [comment]
i use this to look redis data : https://github.com/tiny-craft/tiny-rdm .if there is other redis desktop manager to look data?

**Comment by nalgeon** [comment]
Tiny RDM used to work fine with Redka, but the latest version does not. I'll look into it when I have time.

**Comment by zahariash** [comment]
https://redis.io/insight/ also complains about missing commands.

**Comment by nalgeon** [comment]
Fixed in [v0.5.3](https://github.com/nalgeon/redka/releases/v0.5.3)
