### ISSUE TITLE
Failed to open db with path like "./a/b/c"

### ISSUE THREAD

**Issue by jxs1211** [nalgeon/redka#38]
I got an error when opening a db with file path like:
```
	log.Println("dbPath: ", dbPath)
	db, err := redka.Open(dbPath, o)
```
issue goes like:
```
➜  ktt git:(feat/cli) ✗ go test -timeout 30s -run ^TestRedka$ ktt/backend/db -v
=== RUN   TestRedka
2024/10/03 21:02:59 dbPath:  /root/.KTT/db/sqlite.db
    helper_test.go:38: 
                Error Trace:    /home/going/workspace/myspace/golang/build-together/ktt/backend/db/helper_test.go:38
                Error:          Received unexpected error:
                                disk I/O error: no such file or directory
                Test:           TestRedka
```
I changed the path to ` /root/KTT/db/sqlite.db`(not `.KTT`), it works well, not sure whether it's a bug. Maybe someone can tell me something about it?

**Comment by nalgeon** [comment]
The error means that the directory `/root/.KTT/db` does not exist. I don't see how this is a bug in Redka, but if you think otherwise, please explain your reasoning.

**Comment by jxs1211** [comment]
Sorry, I verified it again, it's my misunderstanding.

**Comment by nalgeon** [comment]
No worries.
