### ISSUE TITLE
Feature Proposal

### ISSUE THREAD

**Issue by CharlyJazz** [nalgeon/redka#4]
Seems redis has a plugin for JSON , what do you think about create that feature using the sqlite json field type? I would like  to help code

**Comment by nalgeon** [comment]
Thanks for the suggestion! Yes, Redis has many plugins. The goal for 1.0 is the five core data types: strings, lists, sets, hashes, and sorted sets. After that — we'll see.

I'll close this for now and we can revisit it after 1.0.

**Comment by c-nv-s** [comment]
I hope this prior/similar art can help you
https://github.com/MirrorFork/redix (note that I'm specifically linking to an old fork and not the latest version from original author)
https://github.com/yob/pgredis

**Comment by c-nv-s** [comment]
I also remember seeing some of Josh Baker's work which could help you 
https://github.com/tidwall/summitdb?tab=readme-ov-file#json-documents
https://github.com/tidwall/redcon
https://github.com/tidwall/resp
