### ISSUE TITLE
Can't use db.scan () or db.scanner () in the Go program

### ISSUE THREAD

**Issue by gsw945** [nalgeon/redka#40]
The functions signature is as follows:

https://github.com/nalgeon/redka/blob/017c0b28f7685311c3948b2e6a531012c8092bd3/internal/rkey/db.go#L149

https://github.com/nalgeon/redka/blob/017c0b28f7685311c3948b2e6a531012c8092bd3/internal/rkey/db.go#L163

---

The required paremeter `ktype` must with type [`core.TypeID`](https://github.com/nalgeon/redka/blob/017c0b28f7685311c3948b2e6a531012c8092bd3/internal/core/core.go#L11), but we can't write code as below:
```go
import "github.com/nalgeon/redka/internal/core"

// example:
// type Logger struct {
// 	DB *redka.DB
// }
// var logger *Logger
// ...
// logger.DB.Key().Scan(0, "*", core.TypeString, 100)
```
due to error as below:
```
could not import github.com/nalgeon/redka/internal/core (invalid use of internal package "github.com/nalgeon/redka/internal/core")compiler[BrokenImport](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#BrokenImport)
Package core provides the core types used by other Redka packages.
```

**Comment by nalgeon** [comment]
Fixed in [v0.5.3](https://github.com/nalgeon/redka/releases/v0.5.3)
