### ISSUE TITLE
Running on Windows over named pipes?

### ISSUE THREAD

**Issue by phrrngtn** [nalgeon/redka#41]
[thought I had already logged this but I am unable to find it. Apologies if it is a repost]

Hi,
I am excited to try out Redka but my main usecase is on Windows (Excel client) and I would like to used named pipes as the transport (to simplify the security, I would create the named pipe in a private directory)

do you think this is feasible? I don't have any experience in golang but I see that there is support from Microsoft for named pipes and the language and your code look pretty modular so I might take a shot at it unless you think it is infeasible or impractical.

thanks,
pjjH

**Comment by nalgeon** [comment]
Hi Paul, thank you for your interest in Redka! My understanding is that Go's networking doesn't support named pipes, so I think it's out of scope for the 1.0 release.

**Comment by phrrngtn** [comment]
Hi Anton,
I did some research into it and asked some of my colleagues who have 
experience with golang and it looks like it may be possible to 
incorporate it in, certainly on Linux. I will make an attempt at it and 
if it works and is not too ugly, I will submit a PR.

thanks again for your work on this project. I think it could end up 
being very useful for improving the performance of a number of my 
Windows-based applications.
