### ISSUE TITLE
Benchmark comparison with relational or nosql databases

### ISSUE THREAD

**Issue by kugesh-Rajasekaran** [nalgeon/redka#9]
I believe it's crucial to benchmark against RDBMS or NoSQL databases, such as Postgres and ScyllaDB, which are the real competitors. This comparison will highlight the value creation offered by this project.

**Comment by nalgeon** [comment]
I don't see them as competitors. So I have no current plans for such comparisons.

The goal here is not to compete with general-purpose database engines. Redka aims to provide a convenient API to work with specific data structures (like maps or sets) with a SQLite backend. No world domination plans.
